version: '3'
services:
  front:
    container_name: optimizer-tool-frontend
    restart: always
    build: optimizer-tool-frontend
    ports:
      - 80:8080
  back:
    container_name: backend
    restart: always
    build: backend
    ports:
      - 5000:5000

